src/objects/Division__c.object
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Division</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Name__c</fullName>
        <label>Parent Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>STU{00000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentManager.cls
public with sharing class StudentManager {

	public static list<Student__c> getStudentsByParent(Id ParentAccId){
		list<Student__c> StudentList = [Select s.Parent_Name__c, s.Name, s.Last_Name__c, s.Id, s.First_Name__c, s.Division__c From Student__c s Where s.Parent_Name__c=:ParentAccId];
		return StudentList;
	}
	
	public static set<Id> getDivisionsSet(Id ParentAccId){
		list<Student__c> StudentList = getStudentsByParent(ParentAccId);
		set<Id> DivisionIds = new set<Id>();
		if(!StudentList.isEmpty()){
			for(Student__c s:StudentList){
				if(s.Division__c != null){
					DivisionIds.add(s.Division__c);
				}
			}
		}
		return DivisionIds;
	}
}